# Configuration constants for CortexFDM

# TCP Socket Settings (replaces virtual serial port)
MOCK_PRINTER_HOST = "127.0.0.1"
MOCK_PRINTER_PORT = 9999
SOCKET_TIMEOUT = 5.0

# Camera / Image Settings
IMAGE_FOLDER = "sample_images"
IMAGE_WIDTH = 384
IMAGE_HEIGHT = 384
JPEG_QUALITY = 95
SAMPLING_INTERVAL_SECONDS = 3

# Cerebras API
CEREBRAS_MODEL = "gemma-4-31b"
CEREBRAS_TEMPERATURE = 0.1
CEREBRAS_REASONING_EFFORT = "low"
CEREBRAS_MAX_TOKENS = 500

# Safety Limits
MAX_TEMPERATURE_CELSIUS = 250
MIN_TEMPERATURE_CELSIUS = 150
MIN_SPEED_PERCENTAGE = 10
MAX_SPEED_PERCENTAGE = 200
