# Configuration constants for CortexFDM

# Virtual Serial Port
MOCK_PRINTER_PORT = "CNCB0"
CONTROLLER_PORT = "CNCA0"
BAUD_RATE = 115200
SERIAL_TIMEOUT = 2.0

# Camera / Image Settings
IMAGE_FOLDER = "sample_images"
IMAGE_WIDTH = 512
IMAGE_HEIGHT = 512
JPEG_QUALITY = 80
SAMPLING_INTERVAL_SECONDS = 3

# Cerebras API
CEREBRAS_MODEL = "gemma-4-31b"
CEREBRAS_TEMPERATURE = 0.1
CEREBRAS_STRICT_MODE = True
CEREBRAS_REASONING_EFFORT = "low"
CEREBRAS_MAX_TOKENS = 500

# Safety Limits
MAX_TEMPERATURE_CELSIUS = 250
MIN_TEMPERATURE_CELSIUS = 150
MIN_SPEED_PERCENTAGE = 10
MAX_SPEED_PERCENTAGE = 200
